export const LOGIN_ACTION = '[actions] login user'
export const LOGOUT_ACTION = '[actions] logout user'
export const AUTH_ACTION = '[actions] do user auth'
export const AUTO_LOGIN_ACTION = '[actions] auth auto-login'
export const AUTO_LOGOUT_ACTION = '[actions] auth log-out'
export const SET_USER_TOKEN_DATA_MUTATION = '[mutations] set user token data'
export const LOADING_SPINNER_SHOW_MUTATION = '[mutations] show loading spinner'
export const SET_AUTO_LOGOUT_MUTATION = '[mutations] set autologout'
export const GET_USER_TOKEN_GETTER = '[getters] auth user token'
export const IS_USER_AUTHENTICATED_GETTER = '[getters] is user autenticated'

export const GET_USER_LEVEL_GETTER = '[getters] user level'
